apply plugin: 'com.android.application'

android {
    namespace = "dk.blekinge.dicerolla"
    compileSdkVersion = 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21

    }
    defaultConfig {
        applicationId = "dk.blekinge.dicerolla"
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 1
        versionName = "1.0"
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        baseline = file("lint-baseline.xml")
    }
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:2.3.0"))

    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Source: https://mvnrepository.com/artifact/androidx.annotation/annotation-jvm
    implementation 'androidx.annotation:annotation-jvm:1.9.1'

    // Source: https://mvnrepository.com/artifact/androidx.constraintlayout/constraintlayout
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // Source: https://mvnrepository.com/artifact/androidx.test.espresso/espresso-core
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    testImplementation 'junit:junit:4.13.2'

}
